-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 00:24:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bichos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bichos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bichos` DEFAULT CHARACTER SET utf8 ;
USE `bichos` ;

-- -----------------------------------------------------
-- Table `bichos`.`Tipo_Organismo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Tipo_Organismo` (
  `id_tipo_organismo` INT NOT NULL AUTO_INCREMENT,
  `tipo_organismo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_organismo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bichos`.`Reino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Reino` (
  `idReino` INT NOT NULL AUTO_INCREMENT,
  `nombreReino` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bichos`.`Phyllum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Phyllum` (
  `idPhyllum` INT NOT NULL AUTO_INCREMENT,
  `Phyllumnombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPhyllum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bichos`.`Clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Clase` (
  `idClase` INT NOT NULL AUTO_INCREMENT,
  `ClaseNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bichos`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Orden` (
  `idOrden` INT NOT NULL AUTO_INCREMENT,
  `Ordennombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bichos`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Familia` (
  `idFamilia` INT NOT NULL AUTO_INCREMENT,
  `FamiliaGenero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFamilia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bichos`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Genero` (
  `idGenero` INT NOT NULL,
  `Generonombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bichos`.`Especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Especie` (
  `idEspecie` INT NOT NULL,
  `Especienombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspecie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bichos`.`Organismos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bichos`.`Organismos` (
  `id_organismos` INT NOT NULL AUTO_INCREMENT,
  `nombre_comun` VARCHAR(80) NOT NULL,
  `nombre_cientifico` VARCHAR(90) NOT NULL,
  `caracteristicas` TINYTEXT NOT NULL,
  `tiempo_de_vida` FLOAT NOT NULL,
  `Tipo_Organismo_id_tipo_organismo` INT NOT NULL,
  `Reino_idReino` INT NOT NULL,
  `Phyllum_idPhyllum` INT NOT NULL,
  `Clase_idClase` INT NOT NULL,
  `Orden_idOrden` INT NOT NULL,
  `Familia_idFamilia` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  `Especie_idEspecie` INT NOT NULL,
  PRIMARY KEY (`id_organismos`),
  INDEX `fk_Organismos_Tipo_Organismo_idx` (`Tipo_Organismo_id_tipo_organismo` ASC) VISIBLE,
  INDEX `fk_Organismos_Reino1_idx` (`Reino_idReino` ASC) VISIBLE,
  INDEX `fk_Organismos_Phyllum1_idx` (`Phyllum_idPhyllum` ASC) VISIBLE,
  INDEX `fk_Organismos_Clase1_idx` (`Clase_idClase` ASC) VISIBLE,
  INDEX `fk_Organismos_Orden1_idx` (`Orden_idOrden` ASC) VISIBLE,
  INDEX `fk_Organismos_Familia1_idx` (`Familia_idFamilia` ASC) VISIBLE,
  INDEX `fk_Organismos_Genero1_idx` (`Genero_idGenero` ASC) VISIBLE,
  INDEX `fk_Organismos_Especie1_idx` (`Especie_idEspecie` ASC) VISIBLE,
  CONSTRAINT `fk_Organismos_Tipo_Organismo`
    FOREIGN KEY (`Tipo_Organismo_id_tipo_organismo`)
    REFERENCES `bichos`.`Tipo_Organismo` (`id_tipo_organismo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organismos_Reino1`
    FOREIGN KEY (`Reino_idReino`)
    REFERENCES `bichos`.`Reino` (`idReino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organismos_Phyllum1`
    FOREIGN KEY (`Phyllum_idPhyllum`)
    REFERENCES `bichos`.`Phyllum` (`idPhyllum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organismos_Clase1`
    FOREIGN KEY (`Clase_idClase`)
    REFERENCES `bichos`.`Clase` (`idClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organismos_Orden1`
    FOREIGN KEY (`Orden_idOrden`)
    REFERENCES `bichos`.`Orden` (`idOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organismos_Familia1`
    FOREIGN KEY (`Familia_idFamilia`)
    REFERENCES `bichos`.`Familia` (`idFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organismos_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `bichos`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organismos_Especie1`
    FOREIGN KEY (`Especie_idEspecie`)
    REFERENCES `bichos`.`Especie` (`idEspecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
